name: Publish Crate

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write  # For potential future cargo login (not needed with token)

    steps:
    - uses: actions/checkout@v4

    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable
        components: clippy

    - name: Cache Dependencies
      uses: Swatinem/rust-cache@v2

    - name: Run Clippy (pre-publish check)
      run: cargo clippy -- -D warnings

    - name: Run Tests (pre-publish check)
      run: cargo test --verbose

    - name: Publish to crates.io
      env:
        CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
      run: cargo publish
